
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miriam
 */
public class Meniu extends javax.swing.JFrame {

   List<? extends Alimente> meniu = Arrays.asList(
        new DeBaut("Silva Bruna", 7, 330),
        new DeBaut("Apa plata", 5, 500),
        new DeMancat("Pizza Quatro Formaggi", 26, 350),
        new DeMancat("Cheeseburger", 30, 450),
        new DeMancat("Papanasi", 14, 400)
    );
    private DefaultListModel modelComanda= new DefaultListModel();
    private DefaultComboBoxModel modelMeniu= new DefaultComboBoxModel();
    private Comparator<Alimente> dupaPret = (a1,a2)-> (a1.getPret())-(a2.getPret());
    private Comparator<Alimente> alfabetic = (a1,a2) -> a1.getDenumire().compareTo(a2.getDenumire());
    
    public Meniu() {
        initComponents();
        refreshModelComanda(Collections.emptyList());
        refreshModelOptiuni();
        listComanda.setModel(modelComanda);
        listOptiuni.setModel(modelMeniu);
    }
    private void refreshModelComanda(List<? extends Alimente> m) {
        modelComanda.clear();
        for (Alimente a : m) {
            modelComanda.addElement(a);
        }
    }
    private void refreshModelOptiuni() {
        //modelMeniu.clear();
        for (Alimente a : meniu) {
            modelMeniu.addElement(a);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listComanda = new javax.swing.JList<>();
        btnSterge = new javax.swing.JButton();
        listOptiuni = new javax.swing.JComboBox<>();
        btnAdauga = new javax.swing.JButton();
        rbtnPret = new javax.swing.JRadioButton();
        rbtnAlfabetic = new javax.swing.JRadioButton();
        btnTotal = new javax.swing.JButton();
        fieldTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listComanda);

        btnSterge.setText("Sterge");
        btnSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergeActionPerformed(evt);
            }
        });

        btnAdauga.setText("Adauga");
        btnAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnPret);
        rbtnPret.setText("dupa pret");
        rbtnPret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPretActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnAlfabetic);
        rbtnAlfabetic.setText("alfabetic");
        rbtnAlfabetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAlfabeticActionPerformed(evt);
            }
        });

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTotal)
                        .addGap(18, 18, 18)
                        .addComponent(fieldTotal))
                    .addComponent(listOptiuni, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSterge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnAlfabetic))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdauga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(rbtnPret))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdauga)
                            .addComponent(rbtnPret))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSterge)
                            .addComponent(rbtnAlfabetic)))
                    .addComponent(listOptiuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergeActionPerformed
         modelComanda.remove(listComanda.getSelectedIndex());
         
    }//GEN-LAST:event_btnStergeActionPerformed

    private void btnAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugaActionPerformed
        modelComanda.addElement(listOptiuni.getSelectedItem());
      
    }//GEN-LAST:event_btnAdaugaActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        Collection<Alimente> model=Collections.list(modelComanda.elements());
        int total;
        total=model.stream().mapToInt((Alimente p)->p.getPret()).sum();
        fieldTotal.setText(Integer.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void rbtnPretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPretActionPerformed
        Collection<Alimente> list=Collections.list(modelComanda.elements());
        List<Alimente> arr;
        arr=list.stream().sorted(dupaPret).collect(Collectors.toList());
        refreshModelComanda(arr);
        
    }//GEN-LAST:event_rbtnPretActionPerformed

    private void rbtnAlfabeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAlfabeticActionPerformed
        Collection<Alimente> list=Collections.list(modelComanda.elements());
        List<Alimente> arr;
        arr=list.stream().sorted(alfabetic).collect(Collectors.toList());
        refreshModelComanda(arr);
    }//GEN-LAST:event_rbtnAlfabeticActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meniu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdauga;
    private javax.swing.JButton btnSterge;
    private javax.swing.JButton btnTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listComanda;
    private javax.swing.JComboBox<String> listOptiuni;
    private javax.swing.JRadioButton rbtnAlfabetic;
    private javax.swing.JRadioButton rbtnPret;
    // End of variables declaration//GEN-END:variables
}
